#!/bin/sh
#
# Copyright 2014 Bright Things Unlimited
#

# Check each rule individually

if ! uci show firewall | grep ".name=anondns" >/dev/null; then

uci batch <<-EOF
	add firewall rule
	set firewall.@rule[-1].name=anondns
	set firewall.@rule[-1].src=anon
	set firewall.@rule[-1].src_dport=53
	set firewall.@rule[-1].target=DNAT
	set firewall.@rule[-1].proto=tcp udp
	set firewall.@rule[-1].dest_port=9053
	set firewall.@rule[-1].dest_ip=10.191.0.1
	commit firewall
EOF

fi

if ! uci show firewall | grep ".name=anonfwd" >/dev/null; then

uci batch <<-EOF
	add firewall rule
	set firewall.@rule[-1].name=anonfwd
	set firewall.@rule[-1].src=anon
	set firewall.@rule[-1].src_dport=1-65535
	set firewall.@rule[-1].target=DNAT
	set firewall.@rule[-1].proto=tcp
	set firewall.@rule[-1].dest_port=9040
	set firewall.@rule[-1].dest_ip=10.191.0.1
	commit firewall
EOF

fi

if ! uci show firewall | grep ".name=onion" >/dev/null; then

uci batch <<-EOF
	add firewall rule
	set firewall.@rule[-1].name=onion
	set firewall.@rule[-1].src=lan
	set firewall.@rule[-1].dst=lan
	set firewall.@rule[-1].target=DNAT
	set firewall.@rule[-1].proto=tcp udp
	set firewall.@rule[-1].dest_port=9040
	set firewall.@rule[-1].dip=10.192.0.0/10
	commit firewall
EOF

fi

exit 0










