#!/bin/sh /etc/rc.common
# Copyright (C) 2014 Bright Things UN Ltd.
#

START=13

boot() {

	# Create /tmp/mtdconfig if it does not exist
	[ -d /tmp/mtdconfig ] || mkdir /tmp/mtdconfig

	# Attempt to mount /dev/mtdblock5 on /config - exit if impossible
	[ mount /dev/mtdblock5 /tmp/mtdconfig ] || return 1

	PASSWD=`cat /etc/shadow | grep root | sed 's/^root://g' | sed 's/:.*$//g'`
	DEFAULT_PASSWORD=`cat /tmp/mtdconfig/root`

	[ -z "${PASSWD}" ] && echo -e "${DEFAULT_PASSWORD}\n${DEAULT_PASSWORD}" | passwd root >/dev/null
	
	# Finally unmount and remove the temporary mount point
	[ umount /tmp/mtdconfig ] && rmdir /tmp/mtdconfig

}

